### ISSUE TITLE
Undefined Variable

### ISSUE THREAD

**Issue by rachel9494** [livebg/artwork#3]
Hello, I have an error with this gem and I am probably overlooking something easy or obvious. Using Rails 4.2.0, Artwork 1.0.0, and The Ruby Racer 0.12.2.

So I installed the gems and saved the mentioned variables from the readme in the artwork.rb initializer. Placed this:

`<%= activate_resolution_independence %>`

BELOW the meta data for viewport info in my application.html.erb, restarted my server, I get this error:

`NameError in StaticPages#home

undefined local variable or method 'activate_resolution_independence'`

What am I missing?

**Comment by bliof** [comment]
You have to include [`Artwork::Controller`](https://github.com/livebg/artwork#usage-example) in your `ApplicationController`. It adds the view helpers and the filter for configuring the gem for the current request. gl & hf :)

**Comment by rachel9494** [comment]
It IS included:

```
class ApplicationController < ActionController::Base

  Artwork::Controller
```

Edit: Just some more info. Yes, I had already placed that in my application controller before posting this issue. Also put the `include Artwork::Model` code in my relevant model. Sorry, should have put that in my first post. I have also tried reinstalling the gem and restarted my server several times.

**Comment by mitio** [comment]
@rachel9494 is the code you've shown above copy-pasted from your codebase? Because you're missing an `include` statement–it should read like this:

``` ruby
class ApplicationController < ActionController::Base
  include Artwork::Controller
```

**Comment by rachel9494** [comment]
Ah, that's the issue! I put "include" in the model but not in the controller! I just copied the code from the readme which didn't have the word include for the controller part (but did for the model). Thanks!! (learning a lot about formatting)
